import { generateText } from "ai";
import { getLanguageModel } from "@/lib/ai/providers";
import { createDocumentHandler } from "@/lib/artifacts/server";

function extractImageBase64(files: Array<{ mediaType?: string; uint8Array: Uint8Array }>) {
  const imageFile = files.find((f) => f.mediaType?.startsWith("image/"));
  if (!imageFile) {
    throw new Error("No image generated by the model");
  }
  return Buffer.from(imageFile.uint8Array).toString("base64");
}

export const imageDocumentHandler = createDocumentHandler<"image">({
  kind: "image",
  onCreateDocument: async ({ title, dataStream, modelId }) => {
    const result = await generateText({
      model: getLanguageModel(modelId),
      prompt: title,
    });

    const base64 = extractImageBase64(result.files);

    dataStream.write({
      type: "data-imageDelta",
      data: base64,
      transient: true,
    });

    return base64;
  },
  onUpdateDocument: async ({ description, dataStream, modelId }) => {
    const result = await generateText({
      model: getLanguageModel(modelId),
      prompt: description,
    });

    const base64 = extractImageBase64(result.files);

    dataStream.write({
      type: "data-imageDelta",
      data: base64,
      transient: true,
    });

    return base64;
  },
});
